{% set image_box = "busybox" %}
{% set image_pause = "mirantis.azurecr.io/general/external/pause:3.1" %}
{% set image_cirros = "virtlet/download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img" %}
{% set concurrency = 1 %}
{% set times = 1 %}
{% set replicas = 1 %}
{% set replicas_scaled = 2 %}
{% set namespaces = 1 %}
{% set serviceacc_delay = 60 %}


---
version: 2
title: MOS Kubenetes performance checks
subtasks:
- title: Run a single workload with listing existing kubernetes namespaces
  scenario:
    Kubernetes.list_namespaces: {}
  runner:
    constant:
      concurrency: {{concurrency}}
      times: {{times}}
- title: Run a single workload with create/read/delete namespace
  scenario:
    Kubernetes.create_and_delete_namespace: {}
  runner:
    constant:
      concurrency: {{concurrency}}
      times: {{times}}
- title: Run a single workload with create/read/delete job
  scenario:
    Kubernetes.create_and_delete_job:
      image: {{image_box}}
      command:
      - echo
      - "SUCCESS"
  runner:
    constant:
      concurrency: {{concurrency}}
      times: {{times}}
  contexts:
    namespaces:
      count: {{namespaces}}
      with_serviceaccount: true
      serviceaccount_delay: {{serviceacc_delay}}
- title: Run a single workload with create/read/delete pod with configMap volume
  scenario:
    Kubernetes.create_and_delete_pod_with_configmap_volume:
      image: {{image_box}}
      mount_path: /var/log/check.txt
      subpath: check.txt
      configmap_data:
        check.txt: |
          test
  runner:
    constant:
      concurrency: {{concurrency}}
      times: {{times}}
  contexts:
    namespaces:
      count: {{namespaces}}
      with_serviceaccount: true
      serviceaccount_delay: {{serviceacc_delay}}
- title: Run a single workload with create/delete NodePort service
  scenario:
    Kubernetes.create_and_delete_pod_with_node_port_service:
      image: {{image_box}}
      port: 80
      protocol: TCP
  runner:
    constant:
      concurrency: {{concurrency}}
      times: {{times}}
  contexts:
    namespaces:
      count: {{namespaces}}
      with_serviceaccount: true
      serviceaccount_delay: {{serviceacc_delay}}
    kubernetes.cfg:
      prepoll_delay: 1
- title: Run a single workload with create/read/delete pod
  scenario:
    Kubernetes.create_and_delete_pod:
      image: {{image_box}}
  runner:
    constant:
      concurrency: {{concurrency}}
      times: {{times}}
  contexts:
    namespaces:
      count: {{namespaces}}
      with_serviceaccount: true
      serviceaccount_delay: {{serviceacc_delay}}

