apiVersion: v1
kind: Pod
metadata:
  name: qa-pod
  namespace: qa-space
spec:
  containers:
  - command:
    - /bin/sleep
    - infinity
    env:
    - name: LANG
      value: C.UTF-8
    - name: OS_IDENTITY_API_VERSION
      value: "3"
    - name: OS_AUTH_URL
      valueFrom:
        secretKeyRef:
          key: OS_AUTH_URL
          name: keystone-keystone-admin
    - name: OS_REGION_NAME
      valueFrom:
        secretKeyRef:
          key: OS_REGION_NAME
          name: keystone-keystone-admin
    - name: OS_INTERFACE
      valueFrom:
        secretKeyRef:
          key: OS_INTERFACE
          name: keystone-keystone-admin
    - name: OS_ENDPOINT_TYPE
      valueFrom:
        secretKeyRef:
          key: OS_INTERFACE
          name: keystone-keystone-admin
    - name: OS_PROJECT_DOMAIN_NAME
      valueFrom:
        secretKeyRef:
          key: OS_PROJECT_DOMAIN_NAME
          name: keystone-keystone-admin
    - name: OS_PROJECT_NAME
      valueFrom:
        secretKeyRef:
          key: OS_PROJECT_NAME
          name: keystone-keystone-admin
    - name: OS_USER_DOMAIN_NAME
      valueFrom:
        secretKeyRef:
          key: OS_USER_DOMAIN_NAME
          name: keystone-keystone-admin
    - name: OS_USERNAME
      valueFrom:
        secretKeyRef:
          key: OS_USERNAME
          name: keystone-keystone-admin
    - name: OS_PASSWORD
      valueFrom:
        secretKeyRef:
          key: OS_PASSWORD
          name: keystone-keystone-admin
    - name: OS_DEFAULT_DOMAIN
      valueFrom:
        secretKeyRef:
          key: OS_DEFAULT_DOMAIN
          name: keystone-keystone-admin
    imagePullPolicy: IfNotPresent
# enable this image if rally is not enough, 
# but rally will be needed to be installed manually
    name: ubuntu
    image: ubuntu:20.04
# xrally container has a lot of packages missing. 
# It is better to install rally on ubuntu, than install missing packages on rally image
#    name: rally-perf
#    image: xrally/xrally-openstack:2.1.0
    volumeMounts:
    - mountPath: /artifacts
      name: qa-pv
  dnsPolicy: ClusterFirst
  volumes:
  - emptyDir: {}
    name: pod-tmp
  - name: qa-pv
    persistentVolumeClaim:
      claimName: qa-pvc
