apiVersion: v1
kind: Namespace
metadata:
  name: qa-space
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qa-pv-a
  namespace: qa-space
  labels:
    type: local
spec:
  storageClassName: storage_class
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/artifacts"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qa-pvc-a
  namespace: qa-space
spec:
  storageClassName: storage_class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qa-pv-r
  namespace: qa-space
  labels:
    type: local
spec:
  storageClassName: storage_class
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/artifacts"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qa-pvc-r
  namespace: qa-space
spec:
  storageClassName: storage_class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
