apiVersion: v1
kind: Namespace
metadata:
  name: qa-space
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qa-pv
  namespace: qa-space
  labels:
    type: local
spec:
  storageClassName: volumes-hdd
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/artifacts"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qa-pvc
  namespace: qa-space
spec:
  storageClassName: volumes-hdd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
