apiVersion: v1
kind: Pod
metadata:
  name: rally
  namespace: qa-space
spec:
  containers:
  - command:
    - /bin/sleep
    - infinity
    env:
    - name: LANG
      value: C.UTF-8
    - name: OS_IDENTITY_API_VERSION
      value: "3"
    - name: OS_AUTH_URL
      valueFrom:
        secretKeyRef:
          key: OS_AUTH_URL
          name: keystone-keystone-admin
    - name: OS_REGION_NAME
      valueFrom:
        secretKeyRef:
          key: OS_REGION_NAME
          name: keystone-keystone-admin
    - name: OS_INTERFACE
      valueFrom:
        secretKeyRef:
          key: OS_INTERFACE
          name: keystone-keystone-admin
    - name: OS_ENDPOINT_TYPE
      valueFrom:
        secretKeyRef:
          key: OS_INTERFACE
          name: keystone-keystone-admin
    - name: OS_PROJECT_DOMAIN_NAME
      valueFrom:
        secretKeyRef:
          key: OS_PROJECT_DOMAIN_NAME
          name: keystone-keystone-admin
    - name: OS_PROJECT_NAME
      valueFrom:
        secretKeyRef:
          key: OS_PROJECT_NAME
          name: keystone-keystone-admin
    - name: OS_USER_DOMAIN_NAME
      valueFrom:
        secretKeyRef:
          key: OS_USER_DOMAIN_NAME
          name: keystone-keystone-admin
    - name: OS_USERNAME
      valueFrom:
        secretKeyRef:
          key: OS_USERNAME
          name: keystone-keystone-admin
    - name: OS_PASSWORD
      valueFrom:
        secretKeyRef:
          key: OS_PASSWORD
          name: keystone-keystone-admin
    - name: OS_DEFAULT_DOMAIN
      valueFrom:
        secretKeyRef:
          key: OS_DEFAULT_DOMAIN
          name: keystone-keystone-admin
    imagePullPolicy: IfNotPresent
    name: rally
    image: savex13/xrally-kube:2.1.0
    volumeMounts:
    - mountPath: /artifacts
      name: qa-pv-r
  dnsPolicy: ClusterFirst
  volumes:
  - emptyDir: {}
    name: pod-tmp
  - name: qa-pv-r
    persistentVolumeClaim:
      claimName: qa-pvc-r
