apiVersion: v1
kind: Namespace
metadata:
  name: qa-space
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qa-pvc
  namespace: qa-space
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: toolset
  namespace: qa-space
spec:
  containers:
  - name: toolset
    image: registry.mirantis.com/professional-services-qa/toolset:k0rdent_test_10242025
    imagePullPolicy: IfNotPresent
    command: ["/bin/sleep", "infinity"]
    env:
    - name: LANG
      value: C.UTF-8
    volumeMounts:
      - name: artifacts
        mountPath: /artifacts
  volumes:
    - name: artifacts
      persistentVolumeClaim:
        claimName: qa-pvc
  dnsPolicy: ClusterFirst